Provide a link to the address page from the contract page #395
CityOfZion/dora pull request #426
Opened 2021-11-30 16:47 UTC by LeonardoDizConde

2022-01-18 19:17 UTC, comountainclimber approved these changes

2022-01-21 14:10 UTC, aldo-maciel commented on src/pages/contract/Contract.scss
> +  color: #dd4bf1;
dentro do index.css tem um `:root`
lá tem um var `--pink`
vc pode utilizar dessa forma `color: var(--pink);`

2022-01-21 14:17 UTC, aldo-maciel commented on src/pages/contract/Contract.scss
> +#contract-hash-box{
tenta utilizar mais com class ao invés de id.
id vc acaba sempre limitando o estilo apenas para um elemento

2022-01-21 14:18 UTC, aldo-maciel commented on src/pages/contract/Contract.tsx
> +      if (chain === 'neo3') {
```suggestion
      if (contract && chain === 'neo3') {
```

2022-01-21 14:19 UTC, aldo-maciel requested changes
.

2022-01-27 00:54 UTC, aldo-maciel approved these changes
LGTM

2022-01-27 00:55 UTC, merged