Filter contracts by N3 main net by default
CityOfZion/dora pull request #579
Opened 2022-05-31 20:52 UTC by LeonardoDizConde

2022-05-31 20:52 UTC, lllwvlvwlll commented
Task linked: [CU-2mdxvxu Filter contracts by N3 main net by default](https://app.clickup.com/t/2mdxvxu)

2022-06-01 14:04 UTC, aldo-maciel requested changes

2022-06-01 14:04 UTC, aldo-maciel commented on src/hooks/useFilterState.ts
> +    network: !defaultNetwork ? 'all' : defaultNetwork,
```suggestion
    protocol: defaultProtocol ?? 'all',
    network: defaultNetwork ?? 'all',
```

2022-06-01 16:57 UTC, aldo-maciel approved these changes

2022-06-01 16:58 UTC, merged