use dora-sdk-ts
CityOfZion/dora pull request #620
Opened 2023-03-20 14:14 UTC by ixje

I tried to change the code to use `dora-sdk-ts` interfaces instead of having internal ones, but it turned out to be futile. Ultimately components expected data as specific types such as `ParsedTx` and thus we're not gaining anything. At some point it also became unclear to me what the correct place is for data transformations as I sometimes see it happen in components and other times in reducers. I ended up ditching the branch and am now opting to just make sure we're not doing any manual `fetch()`'s and just use the REST interfaces provided by `dora-sdk-ts` so the switch to backend v2 becomes easy.

fwiw; the dora-sdk-ts version update is not strictly necessary, but we'll have to do that at some point and it's useful in for testing with the `/v2/` backend

2023-03-20 14:25 UTC, ixje commented
@comountainclimber I do not get any errors locally, so I'm not sure what's up with circleci

2023-03-22 00:56 UTC, comountainclimber commented
Not quite sure what is going on with the type check step but it seems to be finding many type errors 🤔 :
<img width="900" alt="Screenshot 2023-03-21 at 6 55 17 PM" src="https://user-images.githubusercontent.com/13072035/226774430-d6d6a95a-0d4e-4259-a22a-f6a1e733e588.png">

2023-03-22 00:57 UTC, comountainclimber commented
Could it be related to the massive diff in `package-lock.json` being introduced with this PR?

2023-03-22 01:00 UTC, comountainclimber requested changes
Lets get this type check thing sorted out before merging 😅

2023-03-22 01:00 UTC, comountainclimber commented on src/actions/transactionActions.ts
> +          )
nitpick:
```typescript
  return result.items.map(
             ({time, hash, size}) =>
              ({
                size,
                time: Number(tx.time),
                txid: hash,
                protocol: protocol,
                network: network,
              } as Transaction),
          )
```

2023-03-22 01:00 UTC, comountainclimber commented on src/utils/mockData.ts
> +      size: 666,
😈

2023-03-22 07:30 UTC, ixje commented
> Could it be related to the massive diff in `package-lock.json` being introduced with this PR?

No idea why it's there. Even regenerating didn't solve it, but merging the other PR (part 2) and then rebasing this on top of it and rolling back the `package-lock.json` changes finally solved it. Thanks for the hint!

2023-03-22 07:30 UTC, ixje commented on src/utils/mockData.ts
> +      size: 666,
was already there 😅

2023-03-22 07:34 UTC, ixje commented on src/actions/transactionActions.ts
> +          )
I did not know you could do that 👍

2023-03-22 14:25 UTC, comountainclimber approved these changes

2023-03-22 15:33 UTC, merged