CU-86a0dc4dp - requesting block/transaction details also requests a lot of unnecessary data
CityOfZion/dora pull request #645
Opened 2023-08-14 21:51 UTC by Thacryba

2023-08-14 21:51 UTC, lllwvlvwlll commented
Task linked: [CU-86a0dc4dp requesting block/transaction details also requests a lot of unnecessary data](https://app.clickup.com/t/86a0dc4dp)

2023-08-15 06:40 UTC, ixje requested changes
left a comment on clickup

2023-08-15 17:27 UTC, ixje approved these changes

2023-08-15 17:27 UTC, ixje commented
Tested, looks good!

2023-08-18 15:24 UTC, merged