CU-86a0jbrvr - change pagination style
CityOfZion/dora pull request #652
Opened 2023-08-24 17:51 UTC by Thacryba

2023-08-24 17:51 UTC, lllwvlvwlll commented
Task linked: [CU-86a0jbrvr change pagination style](https://app.clickup.com/t/86a0jbrvr)

2023-08-25 07:54 UTC, ixje requested changes
Please see Clickup for the changes

2023-08-29 13:32 UTC, ixje commented
Looks good! :1st_place_medal:

2023-08-29 13:32 UTC, ixje approved these changes

2023-08-29 13:32 UTC, merged